# permissions for end users to view lambdaconcurrencyscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lambdaconcurrencyscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lambda-con-scaler-operator
    app.kubernetes.io/part-of: lambda-con-scaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: lambdaconcurrencyscaler-viewer-role
rules:
- apiGroups:
  - aws.operators.jittakal.io
  resources:
  - lambdaconcurrencyscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.operators.jittakal.io
  resources:
  - lambdaconcurrencyscalers/status
  verbs:
  - get
